version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PLEX_UID=1000
      - PLEX_GID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM=claim-f5uqUsQpq4acsP6EuSv6
    ## make sure the directory and files are owned by the user you are setting the plex guy as
    volumes:
      - /home/carnufex/plex/config:/config
      - /home/carnufex/plex/ty:/tv
      - /home/carnufex/plex/movies:/movies
    restart: always
